### ISSUE TITLE
Integration with Images.jl

### ISSUE THREAD

**Issue by giordano** [JuliaAstro/AstroImages.jl#1]
This issue is intended as a continuation of https://github.com/JuliaAstro/FITSIO.jl/issues/18

**Comment by aquatiko** [comment]
Hello @giordano , I am Rohit Kumar from Indian Institute of Information Technology, Gwalior, India. I am a CS undergraduate there. I was going through the GSoC idea list and I am very interested to work on Visualization of astronomical images in Julia as I was previously contributing to Images.jl and have some knowledge of the domain. I went through the docs and resources provided and I want to discuss things further. I am hoping there are some other informal communication channel to discuss things further?

**Comment by giordano** [comment]
Hi, thank you so much for your interest, that's great!  I've setup a room on gitter, https://gitter.im/JuliaAstro/AstroImages.jl, you can join it if you want.  However I'll ask David what's the best channel of communication for him, probably we'll be using something else in the end.

**Comment by Himanshu-Garg** [comment]
Hi!

I am Himanshu Garg, currently an undergraduate student in Information Technology, at IIIT-Delhi. I am interested in astrophysics and astronomy for a long time and would love to spend my summer, working with JuliaAstro. I have a decent experience in Python, Java, C and beginner experience in other languages as well. I also have a decent mathematics background.

I will be obliged to work on this project.
can I start solving this issue if no one is working on it? 

Thanks,
Himanshu Garg
