### ISSUE TITLE
Integration with Plots.jl (or next-gen plotting package)

### ISSUE THREAD

**Issue by giordano** [JuliaAstro/AstroImages.jl#2]
*issue moved here from https://github.com/JuliaAstro/FITSIO.jl/issues/90*

---

Besides integration with `Images.jl` (issue #1), it may be useful to have integration with [`Plots.jl`](https://github.com/JuliaPlots/Plots.jl) (or whatever will be the next-gen plotting package in Julia).  This can be achieved with [plot recipes](http://docs.juliaplots.org/latest/recipes/).  If there are WCS coordinates, they could be automatically used as tics on the axes.

**Comment by sefffal** [comment]
Addressed by #30
