### ISSUE TITLE
Poor interaction with broadcastable but not equal dimensions

### ISSUE THREAD

**Issue by mileslucas** [JuliaAstro/AstroImages.jl#33]
There's a poor interaction between dimensions which should be broadcastable but which are not equal. For example:

```julia
julia> using AstroImages

julia> dark = AstroImage(zeros(1, 10, 10));

julia> raw = AstroImage(ones(5, 10, 10));

julia> calib = raw .- dark
ERROR: DimensionMismatch: Found both lengths 5 and 1 for X
```

this is inconvenient for working with collapsed frames (e.g., master dark frame).

**Comment by sefffal** [comment]
Thanks for the report.
I must confess that I didn't realize this worked with Base arrays. I thought the it only worked if the dimension was missing, not of size 1 (e.g. `rand(10,10,5) .- rand(10,10)`, but obviously this makes sense and is useful.

This behaviour is defined by DimensionalData at the moment. @rafaqz, do you have any ideas?

Similarly, it would also be nice if this would work too:
```
dark = AstroImage(zeros(10,10), (X,Y))
raw = AstroImage(zeros(5,10,10), (Z,X,Y))
raw .- dark
```

**Comment by rafaqz** [comment]
This does work in DimensionalData.jl:

```julia
julia> DimArray(rand(1, 5, 6), (X(10:10:10), Y, Z)) .- DimArray(rand(5, 5, 6), (X(10:10:50), Y, Z))
5×5×6 DimArray{Float64,3} with dimensions:
  X Sampled{Int64} 10:10:50 ForwardOrdered Regular Points,
  Y,
  Z
[:, :, 1]
 10  -0.0910365   -0.0884673   0.275522    -0.38793   0.101441
 20   0.369558    -0.373784    0.00344079  -0.707029  0.36177
 30   0.58627     -0.439195    0.44505     -0.501643  0.326661
 40  -0.00849618  -0.80927     0.348296    -0.392082  0.719088
 50  -0.06214     -0.746178   -0.171731    -0.16981   0.740582
[and 5 more slices...]
```

I'm not sure what is missing in the implementation here.

The second option doesn't actually work in `Base` julia. But DimensionalData.jl has `broadcast_dims` that should work out how to broadcast those together because the dimension information lets it do a lazy permutation.

**Comment by sefffal** [comment]
Thanks @rafaqz!
Looks like I just have to bump the version of DimensionalData used by AstroImages.


`broadcast_dims` is really handy & a nice way to allow adding extra dimensions to a cube without changing your code:
```julia
julia> sci = AstroImage(zeros(7,5,5,),(Z,X,Y));
julia> dark = AstroImage(zeros(5,5),(X,Y));
julia> broadcast_dims(-, sci, dark)
7×5×5 AstroImage{Float64,3} with dimensions: Z , X , Y
[:, :, 1]
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
[and 4 more slices...]
julia> sci = AstroImage(zeros(7,5,5,3),(Z,X,Y,Ti));
julia> broadcast_dims(-, sci, dark)
7×5×5×3 AstroImage{Float64,4} with dimensions: Z , X , Y , Ti
[:, :, 1, 1]
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
[and 14 more slices...]
```

**Comment by rafaqz** [comment]
Ah yes I think there was a relatively recent fix for that.

I don't think people really know about `broadcast_dims` but its super powerful, a lot of Rasters.jl builds on it to generalize across unknown dimensions, for example masking to the `X` and `Y` dims then broadcasting the mask across whatever other dims there are, without ever actually checking.
