### ISSUE TITLE
cmap seems unused in implot

### ISSUE THREAD

**Issue by mamivilledeschenes** [JuliaAstro/AstroImages.jl#42]
I am not been able to modify the color map with `implot`. 
I would expect the following lines to display the image with colormap `ice`. 
Whatever the `cmap` provided, the image is displayed with `magma`. 
```julia
using AstroImages, Plots
file = "Image.fits"
img = AstroImage(file)
implot(img, cmap=:ice)
```

I am able to display with a different colormap using `imview`
```julia
p = imview(img, cmap=:ice)
plot(p, frame=:none)
```
this displays with `cmap=:ice` as expected. 

Is this an issue or me misusing `implot` ?

**Comment by sefffal** [comment]
Thanks for the report @mamivilledeschenes!
This is indeed a regression.


As a workaround you can for now try the following:
```julia
implot(imview(img,cmap=:ice))
```

This is what implot should essentially be doing in the background. I will look into why they have diverged.

**Comment by sefffal** [comment]
Fixed in https://github.com/JuliaAstro/AstroImages.jl/commit/ec88440ff264ce24e2b5b5142ee5732ecf01402a

I'll tag a new release once CI is green. 

Thanks for the bug report!
