### ISSUE TITLE
Error on loading 1st HUD as AstroImage

### ISSUE THREAD

**Issue by aquatiko** [JuliaAstro/AstroImages.jl#8]
AstroImage loads the 1st HUD from the fits file given by default. If the first one is not of image type an error occurs. Eg: [euve.fits](https://fits.gsfc.nasa.gov/samples/EUVEngc4151imgx.fits)
I suggest a patch to iterate over the fits file to find the first valid Image type file and use it as default or raise some suitable error to notify user if there is no such Image type file.

**Comment by giordano** [comment]
The second argument of `AstroImage` is exactly to select the extension :slightly_smiling_face:

**Comment by aquatiko** [comment]
Yeah, I'm familiar with that. I just wanted a patch, for the default behavior from erroring.
